package com.example

import domain.LoanApplication

rule "Approve loan application less than 100"
when
  $l : LoanApplication( amount < 100)
then
  modify( $l ) {
          setApproved ( true )
  }
end

rule "Approve loan application more than 100"
when
  $l : LoanApplication( amount > 100)
then
  modify( $l ) {
          setAmount( 100 ),
          setApproved ( true )
  }
end

rule "Print approved"
when
  $l : LoanApplication( approved == true)
then
  System.out.println("Loan approved for amount = " + $l.getAmount() );
end